"""Convert the bundled R data files into NPZ fixtures for tests/notebooks.

Reads:
  voila/data/do_events.rda      -> tests/data/do_events.npz
  voila/data/ornstein.rda       -> tests/data/ornstein.npz

The .RDS regression checkpoints (oxygen_estimates.RDS, multivariate_inference.RDS)
contain S4 objects that pyreadr cannot decode. Regression against those would
require a working R install with the original voila package; that is documented
as out-of-band per the project plan and not required by the dev loop.

Run from repo root:
    uv run python scripts/dump_r_reference.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pyreadr

REPO_ROOT = Path(__file__).resolve().parent.parent
VOILA_DATA = REPO_ROOT / "voila" / "data"
OUT_DIR = REPO_ROOT / "tests" / "data"


def dump_rda(rda_path: Path, key: str, out_path: Path, sampling_period: float) -> None:
    result = pyreadr.read_r(str(rda_path))
    df = result[key]
    arr = df.to_numpy().astype(np.float64)
    np.savez(out_path, x=arr, sampling_period=np.float64(sampling_period))
    print(f"wrote {out_path.name}: shape={arr.shape}, dt={sampling_period}")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # voila/data/do_events.rda is a zoo time series with deltat=1.
    # The vignette extracts its sampling period via deltat() at runtime;
    # for the fixture we record the natural unit (1 sample per timestep).
    dump_rda(VOILA_DATA / "do_events.rda", "do_events", OUT_DIR / "do_events.npz", 1.0)
    # voila/data/ornstein.rda is the bundled OU realization (length 20001 = tsLength=20000+1)
    # generated by simulate_sde(drift="-x", diffusion="sqrt(1.5)", samplingPeriod=0.001).
    dump_rda(VOILA_DATA / "ornstein.rda", "ornstein", OUT_DIR / "ornstein.npz", 0.001)


if __name__ == "__main__":
    main()
